// 시스템 설정 › 프로젝트의 입력칸 규칙 (React와 DOM 없이): 기간 읽기·쓰기, 자동완성 후보
import type { Project } from '@macfolio/desktop-core/site';

/** 기간: 시작일과 끝(날짜, 또는 '운영 중' 같은 글). 프로젝트의 period는 '2024.12.26 – 2025.02.05' 모양이다 */
export interface Period {
	/** YYYY-MM-DD (input type=date의 값). 비었으면 '' */
	start: string;
	end: string;
	/** 끝 대신 쓰는 글 (예: 운영 중). 있으면 end는 비운다 */
	ongoing: string;
}

const DATE = /(\d{4})\.(\d{1,2})\.(\d{1,2})/;
const toInput = (match: RegExpExecArray | null) =>
	match ? `${match[1]}-${match[2].padStart(2, '0')}-${match[3].padStart(2, '0')}` : '';
const toPeriod = (value: string) => value.replaceAll('-', '.');

/** 기간 글을 읽는다. 날짜 모양이 아니면 null (그대로 글로 고치게 한다) */
export function parsePeriod(text: string | undefined): Period | null {
	if (!text?.trim()) return { start: '', end: '', ongoing: '' };
	const [head, ...rest] = text.split(/\s*[–-]\s*(?=\D|$|\d{4}\.)/);
	const start = DATE.exec(head);
	if (!start || start[0] !== head.trim()) return null;
	const tail = rest.join(' – ').trim();
	if (!tail) return { start: toInput(start), end: '', ongoing: '' };
	const end = DATE.exec(tail);
	if (end && end[0] === tail) return { start: toInput(start), end: toInput(end), ongoing: '' };
	if (/\d/.test(tail)) return null;
	return { start: toInput(start), end: '', ongoing: tail };
}

/** 기간을 글로 쓴다 ('2024.12.26 – 2025.02.05', '2026.02.05 – 운영 중', 끝을 모르면 '2024.10.22 –'). 시작이 없으면 undefined */
export function formatPeriod({ start, end, ongoing }: Period): string | undefined {
	if (!start) return undefined;
	const tail = ongoing.trim() || (end ? toPeriod(end) : '');
	return tail ? `${toPeriod(start)} – ${tail}` : `${toPeriod(start)} –`;
}

/** 자주 쓰는 언어 (GitHub linguist의 이름). 프로젝트들이 쓴 언어가 먼저 오고, 그다음 이 순서 */
const COMMON_LANGUAGES = [
	'TypeScript',
	'JavaScript',
	'Python',
	'Java',
	'Kotlin',
	'Swift',
	'Objective-C',
	'Go',
	'Rust',
	'C',
	'C++',
	'C#',
	'Dart',
	'Ruby',
	'PHP',
	'Scala',
	'Elixir',
	'Erlang',
	'Haskell',
	'OCaml',
	'F#',
	'Clojure',
	'Lua',
	'Perl',
	'R',
	'Julia',
	'MATLAB',
	'Zig',
	'Nim',
	'Solidity',
	'HTML',
	'CSS',
	'SCSS',
	'Less',
	'Vue',
	'Svelte',
	'Astro',
	'MDX',
	'Shell',
	'PowerShell',
	'SQL',
	'PLpgSQL',
	'GLSL',
	'HLSL',
	'WebAssembly',
	'Dockerfile',
	'HCL',
	'YAML',
	'Jupyter Notebook',
	'Assembly',
];

/** 자주 쓰는 기술 (프레임워크·라이브러리·도구·서비스·개념, 700여 개). 프로젝트들이 쓴 것이 먼저 오고, 그다음 이 순서. 같은 이름(대소문자 무시)은 하나로 */
const COMMON_STACKS = [
	// 프론트엔드
	'React',
	'Next.js',
	'Vue',
	'Nuxt',
	'Svelte',
	'SvelteKit',
	'Angular',
	'SolidJS',
	'Astro',
	'Remix',
	'React Router',
	'React Native',
	'Expo',
	'Flutter',
	'Electron',
	'Tauri',
	'Vite',
	'webpack',
	'Turbopack',
	'esbuild',
	'Rollup',
	'Babel',
	'SWC',
	'TailwindCSS',
	'styled-components',
	'Emotion',
	'vanilla-extract',
	'CSS Modules',
	'Sass',
	'PostCSS',
	'shadcn/ui',
	'Radix UI',
	'MUI',
	'Chakra UI',
	'Ant Design',
	'Storybook',
	'Redux',
	'Redux Toolkit',
	'Zustand',
	'Jotai',
	'Recoil',
	'MobX',
	'React Query',
	'TanStack Query',
	'SWR',
	'Apollo Client',
	'React Hook Form',
	'Zod',
	'GSAP',
	'Framer Motion',
	'Motion',
	'Three.js',
	'React Three Fiber',
	'D3.js',
	'Chart.js',
	'Recharts',
	'Mapbox',
	'Leaflet',
	'PWA',
	'Web Components',
	'Lit',
	// 백엔드
	'Node.js',
	'Express',
	'NestJS',
	'Fastify',
	'Hono',
	'Koa',
	'Bun',
	'Deno',
	'Spring Boot',
	'Spring',
	'Django',
	'FastAPI',
	'Flask',
	'Rails',
	'Laravel',
	'ASP.NET Core',
	'Gin',
	'Actix',
	'GraphQL',
	'Apollo Server',
	'tRPC',
	'gRPC',
	'REST API',
	'WebSocket',
	'Socket.IO',
	'Prisma',
	'Drizzle',
	'TypeORM',
	'Sequelize',
	'Mongoose',
	'Knex',
	'JWT',
	'OAuth',
	'Passport',
	'NextAuth',
	// 데이터
	'PostgreSQL',
	'MySQL',
	'MariaDB',
	'SQLite',
	'MongoDB',
	'Redis',
	'Elasticsearch',
	'Supabase',
	'Firebase',
	'Firestore',
	'DynamoDB',
	'PlanetScale',
	'Neon',
	'Turso',
	// 인프라·배포
	'Docker',
	'Docker Compose',
	'Kubernetes',
	'Nginx',
	'Vercel',
	'Netlify',
	'Cloudflare',
	'Cloudflare Workers',
	'Cloudflare Pages',
	'AWS',
	'AWS Lambda',
	'S3',
	'EC2',
	'GCP',
	'Azure',
	'Oracle Cloud',
	'Railway',
	'Render',
	'Fly.io',
	'Heroku',
	'GitHub Actions',
	'GitLab CI',
	'Terraform',
	'Linux',
	// 시험·품질
	'Vitest',
	'Jest',
	'Playwright',
	'Cypress',
	'Testing Library',
	'Storybook',
	'ESLint',
	'Prettier',
	'Biome',
	// 도구·협업
	'pnpm',
	'npm',
	'Yarn',
	'Turborepo',
	'Nx',
	'Git',
	'GitHub',
	'Figma',
	'Notion',
	'Jira',
	'Slack',
	// AI·기타
	'OpenAI API',
	'Gemini API',
	'Claude API',
	'Groq',
	'LangChain',
	'Hugging Face',
	'TensorFlow',
	'PyTorch',
	'Pandas',
	'NumPy',
	'Stripe',
	'Toss Payments',
	'Resend',
	'SendGrid',
	'Turnstile',
	'reCAPTCHA',
	'i18next',
	'Markdown',
	'Mermaid',
	'Milkdown',
	'ProseMirror',
	'TipTap',
	'Unity',
	'Godot',
	'Phaser',
	'Arduino',
	'Raspberry Pi',
	// 프론트엔드 더
	'Preact',
	'Qwik',
	'Gatsby',
	'Ember',
	'Backbone',
	'jQuery',
	'Alpine.js',
	'HTMX',
	'Stimulus',
	'Parcel',
	'Rspack',
	'Snowpack',
	'Tailwind UI',
	'Bootstrap',
	'Bulma',
	'Foundation',
	'Headless UI',
	'Mantine',
	'NextUI',
	'DaisyUI',
	'PrimeReact',
	'Vuetify',
	'Quasar',
	'Element Plus',
	'Pinia',
	'Vuex',
	'XState',
	'RxJS',
	'Immer',
	'Formik',
	'Yup',
	'Valibot',
	'Lottie',
	'Rive',
	'Anime.js',
	'Swiper',
	'Embla',
	'Slick',
	'Lenis',
	'Locomotive Scroll',
	'Babylon.js',
	'PixiJS',
	'p5.js',
	'Canvas API',
	'WebGL',
	'WebGPU',
	'Web Audio API',
	'WebRTC',
	'Service Worker',
	'IndexedDB',
	'Web Workers',
	'Intersection Observer',
	'Chart.js',
	'ECharts',
	'Highcharts',
	'Plotly',
	'Victory',
	'Nivo',
	'visx',
	'AG Grid',
	'TanStack Table',
	'React Table',
	'React Virtualized',
	'react-window',
	'dnd-kit',
	'react-beautiful-dnd',
	'React DnD',
	'React Flow',
	'Konva',
	'Fabric.js',
	'Monaco Editor',
	'CodeMirror',
	'Quill',
	'Slate',
	'Lexical',
	'Draft.js',
	'Editor.js',
	'Toast UI Editor',
	'MDX',
	'remark',
	'rehype',
	'marked',
	'Shiki',
	'Prism',
	'highlight.js',
	'KaTeX',
	'MathJax',
	'date-fns',
	'Day.js',
	'Luxon',
	'Moment.js',
	'Lodash',
	'Ramda',
	'Axios',
	'ky',
	'Fetch API',
	'React Router DOM',
	'TanStack Router',
	'Wouter',
	'Next Auth',
	'Clerk',
	'Auth0',
	'Firebase Auth',
	'Supabase Auth',
	'Lucia',
	'Kakao Login',
	'Naver Login',
	'Google Login',
	'Apple Login',
	'Kakao Map',
	'Naver Map',
	'Google Maps',
	'Kakao Pay',
	'Naver Pay',
	'PortOne',
	'Iamport',
	'Bootpay',
	'PayPal',
	'LemonSqueezy',
	'Paddle',
	// 모바일·데스크톱
	'SwiftUI',
	'UIKit',
	'Jetpack Compose',
	'Android SDK',
	'iOS SDK',
	'Kotlin Multiplatform',
	'Xamarin',
	'.NET MAUI',
	'Ionic',
	'Capacitor',
	'Cordova',
	'NativeScript',
	'Expo Router',
	'React Native Reanimated',
	'Electron Forge',
	'Neutralino',
	'Wails',
	'GTK',
	'Qt',
	'WPF',
	'WinUI',
	// 백엔드 더
	'Spring Security',
	'Spring Data JPA',
	'Spring WebFlux',
	'Spring Batch',
	'JPA',
	'Hibernate',
	'MyBatis',
	'QueryDSL',
	'Lombok',
	'Gradle',
	'Maven',
	'Tomcat',
	'Netty',
	'Vert.x',
	'Quarkus',
	'Micronaut',
	'Ktor',
	'Exposed',
	'Django REST Framework',
	'Celery',
	'SQLAlchemy',
	'Alembic',
	'Pydantic',
	'Uvicorn',
	'Gunicorn',
	'Tornado',
	'Sanic',
	'Sinatra',
	'Hanami',
	'Phoenix',
	'Ecto',
	'Symfony',
	'Slim',
	'CodeIgniter',
	'ASP.NET',
	'Entity Framework',
	'Dapper',
	'SignalR',
	'Blazor',
	'Echo',
	'Fiber',
	'Chi',
	'GORM',
	'sqlc',
	'Axum',
	'Rocket',
	'Tokio',
	'Diesel',
	'SeaORM',
	'Elysia',
	'NestJS GraphQL',
	'Apollo Federation',
	'Relay',
	'urql',
	'Hasura',
	'PostGraphile',
	'Strapi',
	'Payload CMS',
	'Sanity',
	'Contentful',
	'Directus',
	'Ghost',
	'WordPress',
	'Keystone',
	'Medusa',
	'Shopify',
	'Socket.IO Client',
	'ws',
	'MQTT',
	'Kafka',
	'RabbitMQ',
	'NATS',
	'BullMQ',
	'Bull',
	'Agenda',
	'node-cron',
	'Puppeteer',
	'Cheerio',
	'Scrapy',
	'BeautifulSoup',
	'Selenium',
	'Multer',
	'Sharp',
	'FFmpeg',
	'ImageMagick',
	'Nodemailer',
	'Mailgun',
	'Postmark',
	'Amazon SES',
	'Twilio',
	'Solapi',
	'Firebase Cloud Messaging',
	'OneSignal',
	'Web Push',
	'Passport.js',
	'bcrypt',
	'Argon2',
	'OpenID Connect',
	'SAML',
	'Keycloak',
	'Zod OpenAPI',
	'OpenAPI',
	'Swagger',
	'Postman',
	'Insomnia',
	// 데이터 더
	'Oracle Database',
	'SQL Server',
	'CockroachDB',
	'TimescaleDB',
	'InfluxDB',
	'Cassandra',
	'ScyllaDB',
	'Couchbase',
	'CouchDB',
	'Neo4j',
	'ArangoDB',
	'Memcached',
	'Valkey',
	'OpenSearch',
	'Meilisearch',
	'Typesense',
	'Algolia',
	'Pinecone',
	'Weaviate',
	'Qdrant',
	'pgvector',
	'Milvus',
	'Snowflake',
	'BigQuery',
	'Redshift',
	'Databricks',
	'Apache Spark',
	'Apache Airflow',
	'dbt',
	'Flink',
	'Hadoop',
	'Realtime Database',
	'Cloud Storage',
	'Cloud Functions',
	'Cloud Firestore',
	'Amplify',
	'AppSync',
	'Convex',
	'PocketBase',
	'Appwrite',
	'Nhost',
	'Xata',
	'Upstash',
	'Cloudflare D1',
	'Cloudflare KV',
	'Cloudflare R2',
	'Cloudflare Durable Objects',
	// 인프라·배포 더
	'Caddy',
	'Apache HTTP Server',
	'Traefik',
	'HAProxy',
	'Envoy',
	'Istio',
	'Helm',
	'ArgoCD',
	'Jenkins',
	'CircleCI',
	'Travis CI',
	'Bitbucket Pipelines',
	'Ansible',
	'Pulumi',
	'Vagrant',
	'Packer',
	'Podman',
	'containerd',
	'ECS',
	'EKS',
	'Fargate',
	'CloudFront',
	'Route 53',
	'API Gateway',
	'SQS',
	'SNS',
	'EventBridge',
	'Step Functions',
	'Cognito',
	'IAM',
	'RDS',
	'Aurora',
	'ElastiCache',
	'CloudWatch',
	'GKE',
	'Cloud Run',
	'App Engine',
	'Compute Engine',
	'Cloud SQL',
	'Azure Functions',
	'Azure App Service',
	'Azure DevOps',
	'DigitalOcean',
	'Linode',
	'Vultr',
	'Hetzner',
	'Naver Cloud',
	'NCP',
	'Kakao Cloud',
	'Cafe24',
	'Gabia',
	'Cloudflare Tunnel',
	'Cloudflare DNS',
	'ngrok',
	'Tailscale',
	'WireGuard',
	'OpenVPN',
	"Let's Encrypt",
	'Certbot',
	'PM2',
	'systemd',
	'Ubuntu',
	'Debian',
	'Alpine Linux',
	'CentOS',
	'Rocky Linux',
	'macOS',
	'Windows',
	'Bash',
	'Zsh',
	'Make',
	'CMake',
	'Prometheus',
	'Grafana',
	'Loki',
	'Datadog',
	'New Relic',
	'Sentry',
	'LogRocket',
	'OpenTelemetry',
	'Jaeger',
	'Elastic Stack',
	'Kibana',
	'Logstash',
	'Fluentd',
	'Uptime Kuma',
	'Google Analytics',
	'GA4',
	'Google Tag Manager',
	'Mixpanel',
	'Amplitude',
	'PostHog',
	'Hotjar',
	'Plausible',
	'Umami',
	'Lighthouse',
	'Web Vitals',
	'PageSpeed Insights',
	// 시험·품질 더
	'Mocha',
	'Chai',
	'Jasmine',
	'Karma',
	'AVA',
	'Supertest',
	'MSW',
	'Nock',
	'Sinon',
	'Testcontainers',
	'JUnit',
	'Mockito',
	'AssertJ',
	'pytest',
	'unittest',
	'RSpec',
	'Go test',
	'k6',
	'Artillery',
	'JMeter',
	'Locust',
	'Chromatic',
	'Percy',
	'Applitools',
	'axe',
	'Pa11y',
	'SonarQube',
	'CodeClimate',
	'Codecov',
	'Husky',
	'lint-staged',
	'commitlint',
	'Stylelint',
	'oxlint',
	'TypeScript ESLint',
	'Dependabot',
	'Renovate',
	'Changesets',
	'semantic-release',
	// 도구·협업 더
	'Bun Workspaces',
	'Lerna',
	'Rush',
	'Vite Plugin',
	'tsup',
	'unbuild',
	'Bazel',
	'Gradle Kotlin DSL',
	'GitLab',
	'Bitbucket',
	'GitHub Projects',
	'GitHub Pages',
	'GitHub Copilot',
	'Cursor',
	'VS Code',
	'IntelliJ IDEA',
	'WebStorm',
	'Xcode',
	'Android Studio',
	'Confluence',
	'Trello',
	'Asana',
	'Linear',
	'Miro',
	'FigJam',
	'Sketch',
	'Adobe XD',
	'Photoshop',
	'Illustrator',
	'After Effects',
	'Premiere Pro',
	'Blender',
	'Aseprite',
	'Pixel Art',
	'Spine',
	'Tiled',
	'Discord',
	'Zoom',
	'Google Meet',
	'Google Workspace',
	'Microsoft Teams',
	'Zeplin',
	'Storybook Docs',
	'Docusaurus',
	'VitePress',
	'Nextra',
	'MkDocs',
	'Sphinx',
	'Swagger UI',
	'Redoc',
	// AI·기타 더
	'ChatGPT',
	'GPT-4',
	'GPT-4o',
	'Gemini',
	'Claude',
	'Llama',
	'Mistral',
	'DeepSeek',
	'Qwen',
	'Ollama',
	'vLLM',
	'LangGraph',
	'LlamaIndex',
	'Vercel AI SDK',
	'OpenAI Agents SDK',
	'Whisper',
	'ElevenLabs',
	'Fish Audio',
	'Suno',
	'Stable Diffusion',
	'DALL·E',
	'Midjourney',
	'Replicate',
	'fal.ai',
	'Together AI',
	'Hugging Face Transformers',
	'Hugging Face Inference',
	'Sentence Transformers',
	'scikit-learn',
	'Keras',
	'JAX',
	'XGBoost',
	'LightGBM',
	'OpenCV',
	'MediaPipe',
	'YOLO',
	'TensorFlow.js',
	'ONNX',
	'ONNX Runtime',
	'Core ML',
	'Jupyter',
	'Colab',
	'Kaggle',
	'Matplotlib',
	'Seaborn',
	'Streamlit',
	'Gradio',
	'FastAPI + Uvicorn',
	'DeepL API',
	'Google Translate API',
	'Papago API',
	'Naver Clova',
	'Clova OCR',
	'Tesseract',
	'Kakao API',
	'Naver API',
	'공공데이터포털',
	'Open API',
	'RSS',
	'Web Scraping',
	'Unity 2D',
	'Unity 3D',
	'Unreal Engine',
	'GameMaker',
	'Cocos',
	'Phaser 3',
	'Three.js + R3F',
	'Matter.js',
	'Box2D',
	'Rapier',
	'Photon',
	'Mirror',
	'Netcode',
	'Steamworks',
	'Google Play Console',
	'App Store Connect',
	'TestFlight',
	'Firebase Analytics',
	'AdMob',
	'Google AdSense',
	'Unity Ads',
	'ESP32',
	'STM32',
	'MicroPython',
	'ROS',
	'OpenGL',
	'Vulkan',
	'Metal',
	'DirectX',
	'SDL',
	'Pygame',
	'Godot 4',
	'GDScript',
	'Figma Plugin',
	'Chrome Extension',
	'Manifest V3',
	'VS Code Extension',
	'Obsidian Plugin',
	'Raycast Extension',
	'Slack Bot',
	'Discord.js',
	'Telegram Bot API',
	'KakaoTalk Channel',
	'Zapier',
	'n8n',
	'Make',
	'Notion API',
	'Google Sheets API',
	'Google Calendar API',
	'YouTube API',
	'Spotify API',
	'GitHub API',
	'GitHub Actions Toolkit',
	'Octokit',
	'Stripe Checkout',
	'Toss Payments SDK',
	'Web Share API',
	'Clipboard API',
	'Geolocation API',
	'Notification API',
	'View Transitions API',
	'CSS Grid',
	'Flexbox',
	'CSS Animations',
	'CSS Variables',
	'Container Queries',
	'Responsive Design',
	'Dark Mode',
	'i18n',
	'a11y',
	'SEO',
	'PWA',
	'SSR',
	'SSG',
	'ISR',
	'CSR',
	'Monorepo',
	'Micro Frontend',
	'Module Federation',
	'Design System',
	'Atomic Design',
	'Clean Architecture',
	'Hexagonal Architecture',
	'DDD',
	'TDD',
	'BDD',
	'CQRS',
	'Event Sourcing',
	'Microservices',
	'Serverless',
	'Edge Computing',
	'WebSockets',
	'SSE',
	'Long Polling',
	'JWT Auth',
	'Session Auth',
	'OAuth 2.0',
	'RBAC',
	'Rate Limiting',
	'Caching',
	'CDN',
	'Image Optimization',
	'Code Splitting',
	'Tree Shaking',
	'Lazy Loading',
	'Virtual Scrolling',
	'Optimistic UI',
	'Offline First',
	'Real-time Sync',
	'Drag and Drop',
	'Infinite Scroll',
	'Pagination',
	'Full-text Search',
	'Geospatial',
	'Cron Jobs',
	'Webhooks',
	'File Upload',
	'Image Processing',
	'Video Streaming',
	'HLS',
	'Audio Processing',
	'Charts',
	'Maps',
	'Payments',
	'Email',
	'SMS',
	'Push Notifications',
	'Analytics',
	'Logging',
	'Monitoring',
	'CI/CD',
	'Testing',
	'Documentation',
	'Open Source',
];

const unique = (values: string[]) => [...new Set(values.map((value) => value.trim()).filter(Boolean))];

/** 언어 후보: 프로젝트들이 쓴 언어 먼저, 그다음 자주 쓰는 언어 */
export const languageOptions = (projects: readonly Project[]) =>
	unique([...projects.map((project) => project.language), ...COMMON_LANGUAGES]);

/** 기술 후보: 프로젝트들의 기술과 다룰 수 있는 기술(많이 쓴 것부터), 그다음 자주 쓰는 기술 */
export function stackOptions(projects: readonly Project[], extra: readonly string[] = []): string[] {
	const counts = new Map<string, number>();
	for (const name of [...projects.flatMap((project) => project.stack), ...extra]) {
		const key = name.trim();
		if (key) counts.set(key, (counts.get(key) ?? 0) + 1);
	}
	const used = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([name]) => name);
	const seen = new Set(used.map((name) => name.toLowerCase()));
	// 목록 안에서도 같은 이름은 하나만 (분류마다 적다 보면 겹친다)
	const rest = COMMON_STACKS.filter((name) => {
		const key = name.toLowerCase();
		if (seen.has(key)) return false;
		seen.add(key);
		return true;
	});
	return [...used, ...rest];
}

/**
 * 친 글자로 후보를 고른다: 이미 고른 것은 빼고, 앞부분이 맞는 것 먼저, 그다음 중간에 들어 있는 것. 대소문자는 가리지 않는다
 */
export function suggest(options: readonly string[], query: string, chosen: readonly string[] = [], limit = 8) {
	const q = query.trim().toLowerCase();
	const taken = new Set(chosen.map((item) => item.toLowerCase()));
	const pool = options.filter((option) => !taken.has(option.toLowerCase()));
	if (!q) return pool.slice(0, limit);
	const starts = pool.filter((option) => option.toLowerCase().startsWith(q));
	const contains = pool.filter((option) => !option.toLowerCase().startsWith(q) && option.toLowerCase().includes(q));
	return [...starts, ...contains].slice(0, limit);
}
